package id.co.icg.ie.dao.model.app;
// Generated Nov 4, 2015 2:13:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RoleMenu generated by hbm2java
 */
@Entity
@Table(name = "admin_role_menu")
public class AppAdminRoleMenu implements java.io.Serializable {

    private AppAdminRoleMenuId id;

    public AppAdminRoleMenu() {
    }

    public AppAdminRoleMenu(AppAdminRoleMenuId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false))
        , 
        @AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false, length = 8))
    })
    public AppAdminRoleMenuId getId() {
        return this.id;
    }

    public void setId(AppAdminRoleMenuId id) {
        this.id = id;
    }

}
