package id.co.icg.ie.dao.model.app;
// Generated Nov 4, 2015 2:13:32 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleWebMenuId generated by hbm2java
 */
@Embeddable
public class AppAdminRoleMenuId implements java.io.Serializable {

    private long roleId;
    private String menuId;

    public AppAdminRoleMenuId() {
    }

    public AppAdminRoleMenuId(long roleId, String menuId) {
        this.roleId = roleId;
        this.menuId = menuId;
    }

    @Column(name = "role_id", nullable = false)
    public long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }

    @Column(name = "menu_id", nullable = false, length = 8)
    public String getMenuId() {
        return this.menuId;
    }

    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof AppAdminRoleMenuId)) {
            return false;
        }
        AppAdminRoleMenuId castOther = (AppAdminRoleMenuId) other;

        return (this.getRoleId() == castOther.getRoleId()) && ((this.getMenuId() == castOther.getMenuId()) || (this.getMenuId() != null && castOther.getMenuId() != null && this.getMenuId().equals(castOther.getMenuId())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getRoleId();
        result = 37 * result + (getMenuId() == null ? 0 : this.getMenuId().hashCode());
        return result;
    }
}
